### ISSUE TITLE
 [FE] 오시는 길

### ISSUE THREAD

**Issue by WhiteKIM** [goorm-fullstack/GoormHotel#14]

**Comment by WhiteKIM** [comment]
@soheetech @parkjikuk  일단 명세랑 최대한 비슷하게 구현해봤습니다. 혹시 확인해보시고 안맞는 부분 이야기해주시면 수정하겠습니다

**Comment by WhiteKIM** [comment]
한번 확인해주시고, 수정사항 있으면 알려주세요

**Comment by WhiteKIM** [comment]
@soheetech @parkjikuk 통합 후 발생한 문제 해결해서 feature-김경규 브랜치에 반영했습니다. 확인해보시고 문제없으면 merge하겠습니다.

**Comment by soheetech** [comment]
> @soheetech @parkjikuk 통합 후 발생한 문제 해결해서 feature-김경규 브랜치에 반영했습니다. 확인해보시고 문제없으면 merge하겠습니다.

feature -> develop 병합 후 확인하는 걸로 할게요~ 아니면 다른 분들 것도 다 2번씩(feature, develop 각 1번씩) 확인해야 해서요. develop 병합 후 실행해서 이상 없는지 확인해주시고 디테일한 부분은 월요일에 지국님과 fe 디테일 수정하기로 했으니 그 때 같이 체크해서 전달드리겠습니다.
