### ISSUE TITLE
[BE] 패키지(디렉터리) 구조 변경

### ISSUE THREAD

**Issue by soheetech** [goorm-fullstack/GoormHotel#26]

**Comment by soheetech** [comment]
2023.08.29 디렉터리 구조 변경 제안(민종님): 계층형 → 도메인형

**Comment by yss1902** [comment]
디렉터리 구조 변경 제안

개발을 하는 도중 클래스와 패키지가 점점 많아지면서 현재 작업중인 내용에서의 디렉토리가 한눈에 들어오지 않고 계층간 이동도 힘들다고 느껴졌고 전체적인 구조가 더 복잡해질거라 예상했고 (예. IDE상으로 Controller -> Service) 계층형보단 도메인형이 더 적합하다고 생각했고 제안을 드려서 변경하게 되었습니다.

팀원들이 각자 브랜치에서 각자의 도메인에 대한 작업을 할 때 독립성을 높여주고 나중에 있을 프로젝트의 확정성과 버그 수정같은 기능적인 면에서도 도메인형이 더 괜찮다고 판단했습니다.
