### ISSUE TITLE
 [BE] 뉴스레터 구독: 구독 신청 확인 메일 발송까지

### ISSUE THREAD

**Issue by WhiteKIM** [goorm-fullstack/GoormHotel#4]

**Comment by WhiteKIM** [comment]
가입해주셔서 감사합니다~2023-08-22부로 뉴스레터 구독되었습니다.
위의 형식으로 가입하고 만약 뉴스레터를 구독한 경우에 가입과 함께 뉴스레더 구독 신청되었다고 메일을 날려주려고 하는데 괜찮을까요?

**Comment by soheetech** [comment]
> 가입해주셔서 감사합니다~2023-08-22부로 뉴스레터 구독되었습니다. 위의 형식으로 가입하고 만약 뉴스레터를 구독한 경우에 가입과 함께 뉴스레더 구독 신청되었다고 메일을 날려주려고 하는데 괜찮을까요?

어제 얘기한대로 뉴스레터 구독은 회원/비회원 모두 신청 가능하고 구독 신청 확인용 메일 양식은 준비되는대로 전달드리겠습니다. 시안 확인하신거 체크 했으니 답변은 안 주셔도 됩니다!

**Comment by WhiteKIM** [comment]
![뉴스레터 구독 확인](https://github.com/goorm-fullstack/GoormHotel/assets/12975617/4cf3866a-4440-43e5-9817-bd0613c8253d)
메일 발송 확인 완료, API 문서 작성 완료

**Comment by soheetech** [comment]
> 

메일 양식 하단 정보칸에 있는 구분선(copy 위쪽) 중앙 정렬이 안 맞아보이는데 한 번 확인 부탁드립니다. 맞추기 힘드시면 빼주세요.

**Comment by WhiteKIM** [comment]
![image](https://github.com/goorm-fullstack/GoormHotel/assets/12975617/c9931f3a-63a8-404f-8bf2-ae11d6ce8e65)
제거완료

**Comment by soheetech** [comment]
> ![image](https://user-images.githubusercontent.com/12975617/263454973-c9931f3a-63a8-404f-8bf2-ae11d6ce8e65.png) 제거완료

위에 로고 부분은 캡쳐하실 때 잘린 거죠?

**Comment by WhiteKIM** [comment]
네 살짝 짤렸네요
