### ISSUE TITLE
 [BE] 채팅 상담

### ISSUE THREAD

**Issue by WhiteKIM** [goorm-fullstack/GoormHotel#5]
구현중

**Comment by WhiteKIM** [comment]
@soheetech 채팅 서비스 구현 중에 궁금한 점이 있는데, 일단 제가 생각할 때 관리자만 채팅방을 조회해볼 수 있고, 사용자는 방을 파고, 자신이 개설한 방에만 접속가능하도록 할 생각인데 어떻게 생각하시나요?

**Comment by soheetech** [comment]
> @soheetech 채팅 서비스 구현 중에 궁금한 점이 있는데, 일단 제가 생각할 때 관리자만 채팅방을 조회해볼 수 있고, 사용자는 방을 파고, 자신이 개설한 방에만 접속가능하도록 할 생각인데 어떻게 생각하시나요?

현재 생각해둔 디자인이 있긴 한데 내일 모임 시간에 같이 말씀드리겠습니다.

**Comment by WhiteKIM** [comment]
채팅 기능 완료 -> 룸 아이디가 다른 경우에 메시지가 보이지 않는 것 확인, 관리자(테스트 클라이언트) - 클라이언트간의 채팅 기능 확인 완료했습니다. 어드민 페이지 구현 완료한 후에 재시험할 예정
